### ISSUE TITLE
Sharing iP code quality feedback [for @Jayden-Kim-NUS]

### ISSUE THREAD

**Issue by soc-se-script** [Jayden-Kim-NUS/ip#2]
@Jayden-Kim-NUS We did an automated analysis of your code to detect potential areas to improve the code quality. We are sharing the results below, to help you improve the iP code further.

IMPORTANT: Note that the script looked for **just a few easy-to-detect problems only**, and **at-most three example are given** i.e., there can be other areas/places to improve.

### Aspect: Tab Usage

No easy-to-detect issues :+1: 

### Aspect: Naming boolean variables/methods

No easy-to-detect issues :+1: 

### Aspect: Brace Style

Example from [`src/main/java/Arona/Arona.java` lines `70-71`](https://github.com/Jayden-Kim-NUS/ip/blob/e5b7aa8ef1bfd2fbfa146608e25ba5a8d3b153e9/src/main/java/Arona/Arona.java#L70..L71):

```java

            // Other exception
            else {

```

Example from [`src/main/java/Arona/Parser.java` lines `53-54`](https://github.com/Jayden-Kim-NUS/ip/blob/e5b7aa8ef1bfd2fbfa146608e25ba5a8d3b153e9/src/main/java/Arona/Parser.java#L53..L54):

```java

            }
            catch (NumberFormatException e) {

```

Example from [`src/main/java/Arona/Parser.java` lines `79-80`](https://github.com/Jayden-Kim-NUS/ip/blob/e5b7aa8ef1bfd2fbfa146608e25ba5a8d3b153e9/src/main/java/Arona/Parser.java#L79..L80):

```java

            }
            catch (NumberFormatException e) {

``` 

**Suggestion:** As specified by the coding standard, use egyptian style braces.

### Aspect: Package Name Style

Example from [`src/main/java/Arona/Arona.java` lines `1-1`](https://github.com/Jayden-Kim-NUS/ip/blob/e5b7aa8ef1bfd2fbfa146608e25ba5a8d3b153e9/src/main/java/Arona/Arona.java#L1..L1):

```java

package Arona;

```

Example from [`src/main/java/Arona/Command.java` lines `1-1`](https://github.com/Jayden-Kim-NUS/ip/blob/e5b7aa8ef1bfd2fbfa146608e25ba5a8d3b153e9/src/main/java/Arona/Command.java#L1..L1):

```java

package Arona;

```

Example from [`src/main/java/Arona/DialogBox.java` lines `1-1`](https://github.com/Jayden-Kim-NUS/ip/blob/e5b7aa8ef1bfd2fbfa146608e25ba5a8d3b153e9/src/main/java/Arona/DialogBox.java#L1..L1):

```java

package Arona;

``` 

**Suggestion:** Follow the package naming convention specified by the coding standard.

### Aspect: Class Name Style

No easy-to-detect issues :+1: 

### Aspect: Dead Code

No easy-to-detect issues :+1: 

### Aspect: Method Length

Example from [`src/main/java/Arona/Parser.java` lines `27-193`](https://github.com/Jayden-Kim-NUS/ip/blob/e5b7aa8ef1bfd2fbfa146608e25ba5a8d3b153e9/src/main/java/Arona/Parser.java#L27..L193):

```java

    public String parse(String input) throws Exception {

        // Bye command
        if (input.equalsIgnoreCase("bye")) {
            // Process and Reply
            storage.save(taskList);
            return ui.showFarewell();
        }

        // List command
        else if (input.equalsIgnoreCase("list")) {
            // Reply
            return ui.showList(taskList);
        }

        // Delete command
        else if (input.toLowerCase().startsWith("delete ")) {

            // Extract and save task number
            String[] data = input.split("delete ", 2);
            assert data.length == 2 : "delete command should have 2 parts after split";

            // Check if number and save index
            int index;
            try {
                index = Integer.parseInt(data[1]);
            }
            catch (NumberFormatException e) {
                throw new MissingArgumentException(Command.DELETE);
            }

            // Process and Reply
            int listSize = taskList.size() - 1;
            Task removedTask = taskList.remove(index - 1);
            storage.save(taskList);
            return ui.showDelete(listSize, removedTask);
        }

        // Mark and unmark command
        else if (input.toLowerCase().startsWith("mark ") || input.toLowerCase().startsWith("unmark ")) {

            // Extract and save task number
            String[] data = input.split("mark ", 2);
            assert data.length == 2 : "Mark/unmark command should have 2 parts after split";

            // Extract and save action
            boolean action = input.toLowerCase().startsWith("mark");

            // Check if number and save index
            int index;
            try {
                index = Integer.parseInt(data[1]);
            }
            catch (NumberFormatException e) {
                throw new MissingArgumentException(Command.DELETE);
            }

            // Process and Reply
            Task markedTask = taskList.setStatus(index - 1, action);
            storage.save(taskList);
            return ui.showMark(markedTask, action);
        }

        // Todos or events or deadline command
        else if (input.toLowerCase().startsWith("todo ") || input.toLowerCase().startsWith("event ") || input.toLowerCase().startsWith("deadline ")) {

            // Data from command
            String[] data;

            // Extract and save description
            data = input.split(" ", 2);

            // Process
            switch (data[0]) {
                case "todo": {
                    if (data.length != 2 || data[1].isEmpty()) {
                        throw new MissingArgumentException(Command.TODO);
                    }

                    taskList.add(data[1]);
                    break;
                }
                case "deadline": {
                    String[] taskData = data[1].split(" /by ", 2);
                    LocalDate byDate;

                    if (taskData.length != 2) {
                        throw new MissingArgumentException(Command.DEADLINE);
                    }

                    try {
                        byDate = LocalDate.parse(taskData[1]);
                    } catch (DateTimeParseException e) {
                        throw new DateFormatException();
                    }

                    taskList.add(taskData[0], byDate);
                    break;
                }
                case "event": {
                    String[] taskData = data[1].split(" /from | /to ", 3);
                    LocalDate fromDate;
                    LocalDate toDate;

                    if (taskData.length != 3) {
                        throw new MissingArgumentException(Command.EVENT);
                    }

                    try {
                        fromDate = LocalDate.parse(taskData[1]);
                        toDate = LocalDate.parse(taskData[2]);
                    } catch (DateTimeParseException e) {
                        throw new DateFormatException();
                    }

                    taskList.add(taskData[0], fromDate, toDate);
                    break;
                }
            }

            // Process and Reply
            int listSize = taskList.size();
            Task addedTask = taskList.peek();
            storage.save(taskList);
            return ui.showAdd(listSize, addedTask);
        }

        // Find command
        else if (input.toLowerCase().startsWith("find ")) {

            // Extract and save keyword
            String keyword = input.split("find", 2)[1].strip().toLowerCase();

            // Check if empty
            if (keyword.isEmpty()) {
                throw new MissingArgumentException(Command.FIND);
            }

            // Process and Reply
            ArrayList<Task> filteredList = taskList.filter(keyword);
            return ui.showFilteredList(filteredList);
        }

        // Archive
        else if (input.toLowerCase().startsWith("archive ")) {

            // Extract and save file name
            String[] data = input.split("archive ", 2);
            assert data.length == 2 : "archive command should have 2 parts after split";

            // Check if name is more than 260 chars or blank
            if (data[1].isBlank() || data[1].length() > 260) {
                throw new MissingArgumentException(Command.ARCHIVE);
            }

            // Process and Reply
            storage.save(taskList, data[1]);
            taskList.deleteAll();
            storage.save(taskList);
            return ui.showArchive(data[1]);
        }

        // All other unrecognised commands
        else {
            throw new AronaException("Error, unrecognised command.");
        }
    }

``` 

**Suggestion:** Consider applying [SLAP (and other abstraction mechanisms)](https://nus-cs2103-ay2425s1.github.io/website//se-book-adapted/chapters/codeQuality.html#guideline-maximise-readability) to shorten methods e.g., extract some code blocks into separate methods. You may ignore this suggestion if you think a longer method is justified in a particular case.

### Aspect: Class size

No easy-to-detect issues :+1: 

### Aspect: Header Comments

Example from [`src/main/java/Arona/Arona.java` lines `40-43`](https://github.com/Jayden-Kim-NUS/ip/blob/e5b7aa8ef1bfd2fbfa146608e25ba5a8d3b153e9/src/main/java/Arona/Arona.java#L40..L43):

```java

    /**
     * Entry to main logic from GUI
     * @param  input  the unprocessed String input from the user
     */

```

Example from [`src/main/java/Arona/Storage.java` lines `87-90`](https://github.com/Jayden-Kim-NUS/ip/blob/e5b7aa8ef1bfd2fbfa146608e25ba5a8d3b153e9/src/main/java/Arona/Storage.java#L87..L90):

```java

    /**
     * Used for debugging related to data.txt location
     * @return A string that shows the absolute file path of data.txt
     */

```

Example from [`src/main/java/Arona/TaskList.java` lines `64-66`](https://github.com/Jayden-Kim-NUS/ip/blob/e5b7aa8ef1bfd2fbfa146608e25ba5a8d3b153e9/src/main/java/Arona/TaskList.java#L64..L66):

```java

    /**
     * Overloaded method, adds to do task
     */

``` 

**Suggestion:** Ensure method/class header comments follow the format specified in the coding standard, in particular, the phrasing of the overview statement.

### Aspect: Recent Git Commit Message

No easy-to-detect issues :+1: 

### Aspect: Binary files in repo

No easy-to-detect issues :+1: 

----

:information_source: The bot account used to post this issue is un-manned. **Do not reply to this post** (as those replies will not be read). Instead, contact `cs2103@comp.nus.edu.sg` if you want to follow up on this post.

**Comment by Jayden-Kim-NUS** [comment]
Fixed, thanks!
